apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
  labels:
    app: mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api
        # IMPORTANTE: Usamos tu ID de proyecto real aqu√≠
        image: gcr.io/active-cove-479919-p6/mlops-api:latest
        ports:
        - containerPort: 5000
