apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-deployment
  labels:
    app: mlops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
      - name: mlops-web
        image: gcr.io/active-cove-479919-p6/mlops-web:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-service:5000/predict
        # Configuraci√≥n vital para que funcione en la nube
        command:
        - streamlit
        - run
        - app_web.py
        - --server.enableCORS=false
        - --server.enableXsrfProtection=false
        - --server.enableWebsocketCompression=false
        - --server.address=0.0.0.0
