name: Docker Build & Push

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c√≥digo del repo
        uses: actions/checkout@v3

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v2
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: peperidruejo/mlops-api:latest

      - name: Construir y subir Web
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: peperidruejo/mlops-web:latest